version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    env_file: .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE_NAME
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  mongo:
    container_name: mongodb
    image: mongo
    env_file: .env
    volumes:
      - "$MONGO_EXTERNAL_LOC:/data/db"
    restart: always
    ports:
      - $MONGO_PORT:$MONGO_PORT
  mongo_seed:
    container_name: mongo_seed
    build: ./mongo-seed
    depends_on:
      - mongo
