
spring:
  datasource:
    username: depaul
    password: depaul
    url: jdbc:postgresql://localhost:5432/rowr
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
