spring:
  datasource:
    username: depaul
    password: depaul
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:5432/rowr
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: mappings
