spring:
  datasource:
    username: depaul
    password: depaul
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:5432/rowr
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  data:
    mongodb:
      host: ${MONGO_HOSTNAME:localhost}
      port: 27017
      database: rowr
management:
  endpoints:
    web:
      exposure:
        include: mappings
logging:
  level:
    edu.depaul.cdm.se452.rightOfWayRentals: trace